In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/home/prashant/Downloads/pincode/pin_codes.csv')

In [3]:
data.head()

   pincode   districtname statename  serviceable
0   110001  Central Delhi     DELHI            1
1   110002  Central Delhi     DELHI            1
2   110003  Central Delhi     DELHI            1
3   110004  Central Delhi     DELHI            1
4   110005  Central Delhi     DELHI            1

In [4]:
serviceable = data[data['serviceable'] == 1]
serviceable.head()
serviceable.shape

(1478, 4)

In [5]:
serviceable_districts = serviceable['districtname'].unique()
serviceable_districts

array(['Central Delhi', 'North Delhi', 'North West Delhi',
       'South West Delhi', 'South Delhi', 'West Delhi', 'East Delhi',
       'North East Delhi', 'New Delhi', 'Gurgaon', 'Faridabad',
       'Panchkula', 'Mohali', 'Chandigarh', 'Ghaziabad',
       'Gautam Buddha Nagar', 'Jaipur', 'Ahmedabad', 'Gandhi Nagar',
       'Mumbai', 'Thane', 'Pune', 'Nashik', 'Hyderabad', 'K.V.Rangareddy',
       'Bengaluru', 'Bangalore Rural', 'Kolar', 'Chennai', 'Kanchipuram',
       'Tiruvallur', 'Kolkata', 'Howrah', 'Hooghly'], dtype=object)

In [6]:
cityname_map = {'Central Delhi' : 'Delhi', 'North Delhi' : 'Delhi', 'North West Delhi': 'Delhi', 'South West Delhi': 'Delhi',
                'West Delhi': 'Delhi','East Delhi': 'Delhi','East Delhi': 'Delhi','New Delhi': 'Delhi', 'South Delhi': 'Delhi', 'Gautam Buddha Nagar': 'Noida'
               , 'K.V.Rangareddy': 'Shamshabad', 'Bangalore Rural': 'Bangalore', 'Bangalore Rural': 'Bangalore', 'North East Delhi': 'Delhi'}

In [7]:
serviceable['cityname'] = serviceable['districtname'].apply(lambda dist: cityname_map.get(dist, dist))

/home/prashant/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [1]:
serviceable.head()

NameError: name 'serviceable' is not defined

In [9]:
serviceable.to_csv('out.csv', index=False)

In [10]:
pin_lat_long = pd.read_csv("/home/prashant/PycharmProjects/medulla/data_models/pincodes.csv")

In [34]:
pin_lat_long.head()

    latitude   longitude  pincode
0  19.864269   79.343739   442901
1  19.852595   79.492886   442701
2  23.143722  111.785937   441226
3  19.918415   80.232131   442604
4  20.056226   79.166141   442902

In [12]:
final = serviceable.set_index('pincode').join(pin_lat_long.set_index('pincode'))
final.columns

Index(['districtname', 'statename', 'serviceable', 'cityname', 'latitude',
       'longitude'],
      dtype='object')

In [13]:
final = final.drop_duplicates()
print(final.shape, final.columns)
absent = final[final['latitude'].apply(lambda x: pd.isnull(x))]
print(absent.shape, absent.columns)

(1153, 6) Index(['districtname', 'statename', 'serviceable', 'cityname', 'latitude',
       'longitude'],
      dtype='object')
(25, 6) Index(['districtname', 'statename', 'serviceable', 'cityname', 'latitude',
       'longitude'],
      dtype='object')

In [14]:
absent['pincode_city'] = absent.apply(lambda row: "{},{}".format(row.cityname, row.name), axis=1)

/home/prashant/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [15]:
absent['pincode_city'].values

array(['Delhi,110050', 'Delhi,110098', 'Delhi,110100', 'Gurgaon,120022',
       'Faridabad,121006', 'Panchkula,134105', 'Chandigarh,160005',
       'Ghaziabad,201004', 'Noida,201305', 'Jaipur,302004',
       'Ahmedabad,380003', 'Gandhi Nagar,382009', 'Mumbai,400023',
       'Thane,401104', 'Pune,411067', 'Hyderabad,500021',
       'Shamshabad,500104', 'Bengaluru,560044', 'Bangalore,560116',
       'Chennai,600008', 'Kanchipuram,600016', 'Tiruvallur,600058',
       'Kolkata,700001', 'Howrah,711102', 'Hooghly,712101'], dtype=object)

In [16]:
absent.to_csv("/home/prashant/PycharmProjects/medulla/data_models/lat_long_absent_pincodes.csv")

In [17]:
serviceable1.shape

NameError: name 'serviceable1' is not defined

In [ ]:
serviceable.shape

In [ ]:
final.shape

In [ ]:
pin_lat_long1.shape

In [ ]:
absent.index.unique()

In [ ]:
absent

In [ ]:
absent.columns

In [85]:
frame = pd.DataFrame()

In [86]:
frame['cityname'] = df['cityname'].unique()

In [87]:
frame

        cityname
0          Delhi
1        Gurgaon
2      Faridabad
3      Panchkula
4         Mohali
5     Chandigarh
6      Ghaziabad
7          Noida
8         Jaipur
9      Ahmedabad
10  Gandhi Nagar
11        Mumbai
12         Thane
13          Pune
14        Nashik
15     Hyderabad
16    Shamshabad
17     Bengaluru
18     Bangalore
19         Kolar
20       Chennai
21   Kanchipuram
22    Tiruvallur
23       Kolkata
24        Howrah
25       Hooghly

In [52]:
df = pd.read_csv("/home/prashant/Downloads/pincode/mapped_with_City.csv")
df['cityname'].unique()

array(['Delhi', 'Gurgaon', 'Faridabad', 'Panchkula', 'Mohali',
       'Chandigarh', 'Ghaziabad', 'Noida', 'Jaipur', 'Ahmedabad',
       'Gandhi Nagar', 'Mumbai', 'Thane', 'Pune', 'Nashik', 'Hyderabad',
       'Shamshabad', 'Bengaluru', 'Bangalore', 'Kolar', 'Chennai',
       'Kanchipuram', 'Tiruvallur', 'Kolkata', 'Howrah', 'Hooghly'],
      dtype=object)

In [41]:
import requests
import json

In [53]:
URL = "https://maps.googleapis.com/maps/api/geocode/json"

In [54]:
def get_lat_long(location):
	# defining a params dict for the parameters to be sent to the API
	PARAMS = {'address':location, 'key': "AIzaSyCdN_BqmYYDLUhv9QqO0MrL6qG7L1HUN3M"}
	 
	# sending get request and saving the response as response object
	r = requests.get(url = URL, params = PARAMS)
	 
	# extracting data in json format
	data = r.json()
	print(data)
	# extracting latitude, longitude and formatted address 
	# of the first matching location
    
	latitude = data['results'][0]['geometry']['location']['lat']
	longitude = data['results'][0]['geometry']['location']['lng']
	formatted_address = data['results'][0]['formatted_address']
	 
	# printing the output
	print("Latitude:%s\nLongitude:%s\nFormatted Address:%s"
	      %(latitude, longitude,formatted_address))

	return (latitude, longitude)

In [59]:
xs = df['cityname'].unique()

In [60]:
xs

array(['Delhi', 'Gurgaon', 'Faridabad', 'Panchkula', 'Mohali',
       'Chandigarh', 'Ghaziabad', 'Noida', 'Jaipur', 'Ahmedabad',
       'Gandhi Nagar', 'Mumbai', 'Thane', 'Pune', 'Nashik', 'Hyderabad',
       'Shamshabad', 'Bengaluru', 'Bangalore', 'Kolar', 'Chennai',
       'Kanchipuram', 'Tiruvallur', 'Kolkata', 'Howrah', 'Hooghly'],
      dtype=object)

In [61]:
final_lat_long = {}
for x in xs:
    print("cityname {}".format(x))
    lat_long = get_lat_long(x)
    final_lat_long[x] = lat_long

cityname Delhi
{'results': [{'address_components': [{'long_name': 'Delhi', 'short_name': 'DL', 'types': ['administrative_area_level_1', 'locality', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Delhi, India', 'geometry': {'bounds': {'northeast': {'lat': 28.881338, 'lng': 77.3484578}, 'southwest': {'lat': 28.412593, 'lng': 76.83806899999999}}, 'location': {'lat': 28.7040592, 'lng': 77.10249019999999}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 28.881338, 'lng': 77.3484578}, 'southwest': {'lat': 28.412593, 'lng': 76.83806899999999}}}, 'place_id': 'ChIJLbZ-NFv9DDkRQJY4FbcFcgM', 'types': ['administrative_area_level_1', 'locality', 'political']}], 'status': 'OK'}
Latitude:28.7040592
Longitude:77.10249019999999
Formatted Address:Delhi, India
cityname Gurgaon
{'results': [{'address_components': [{'long_name': 'Gurugram', 'short_name': 'Gurugram', 'types': ['locality', 'political']}, {'long_name': 'Gurgaon', 'short_name': 'Gurgaon', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Haryana', 'short_name': 'HR', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Gurugram, Haryana, India', 'geometry': {'bounds': {'northeast': {'lat': 28.5458783, 'lng': 77.1226452}, 'southwest': {'lat': 28.303795, 'lng': 76.85691829999999}}, 'location': {'lat': 28.4594965, 'lng': 77.0266383}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 28.5458783, 'lng': 77.1226452}, 'southwest': {'lat': 28.303795, 'lng': 76.85691829999999}}}, 'place_id': 'ChIJWYjjgtUZDTkRHkvG5ehfzwI', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:28.4594965
Longitude:77.0266383
Formatted Address:Gurugram, Haryana, India
cityname Faridabad
{'results': [{'address_components': [{'long_name': 'Faridabad', 'short_name': 'Faridabad', 'types': ['locality', 'political']}, {'long_name': 'Faridabad', 'short_name': 'Faridabad', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Haryana', 'short_name': 'HR', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Faridabad, Haryana, India', 'geometry': {'bounds': {'northeast': {'lat': 28.5137834, 'lng': 77.38977129999999}, 'southwest': {'lat': 28.2912872, 'lng': 77.2483772}}, 'location': {'lat': 28.4089123, 'lng': 77.3177894}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 28.5137834, 'lng': 77.38977129999999}, 'southwest': {'lat': 28.2912872, 'lng': 77.2483772}}}, 'place_id': 'ChIJsSSk9RXcDDkR8uBQyHYF9eQ', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:28.4089123
Longitude:77.3177894
Formatted Address:Faridabad, Haryana, India
cityname Panchkula
{'results': [{'address_components': [{'long_name': 'Panchkula', 'short_name': 'Panchkula', 'types': ['locality', 'political']}, {'long_name': 'Panchkula', 'short_name': 'Panchkula', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Haryana', 'short_name': 'HR', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Panchkula, Haryana, India', 'geometry': {'bounds': {'northeast': {'lat': 30.7625199, 'lng': 76.9099148}, 'southwest': {'lat': 30.64249, 'lng': 76.81474089999999}}, 'location': {'lat': 30.6942091, 'lng': 76.860565}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 30.7625199, 'lng': 76.9099148}, 'southwest': {'lat': 30.64249, 'lng': 76.81474089999999}}}, 'place_id': 'ChIJV7ei1m6TDzkR8EAbBtdohok', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:30.6942091
Longitude:76.860565
Formatted Address:Panchkula, Haryana, India
cityname Mohali
{'results': [{'address_components': [{'long_name': 'Sahibzada Ajit Singh Nagar', 'short_name': 'SAS Nagar', 'types': ['locality', 'political']}, {'long_name': 'Sahibzada Ajit Singh Nagar', 'short_name': 'SAS Nagar', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Punjab', 'short_name': 'PB', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Sahibzada Ajit Singh Nagar, Punjab, India', 'geometry': {'bounds': {'northeast': {'lat': 30.7514252, 'lng': 76.7579126}, 'southwest': {'lat': 30.6452228, 'lng': 76.6368483}}, 'location': {'lat': 30.7046486, 'lng': 76.71787259999999}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 30.7514252, 'lng': 76.7579126}, 'southwest': {'lat': 30.6452228, 'lng': 76.6368483}}}, 'place_id': 'ChIJH_imbZDuDzkR2AjlbPGYKVE', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:30.7046486
Longitude:76.71787259999999
Formatted Address:Sahibzada Ajit Singh Nagar, Punjab, India
cityname Chandigarh
{'results': [{'address_components': [{'long_name': 'Chandigarh', 'short_name': 'Chandigarh', 'types': ['locality', 'political']}, {'long_name': 'Chandigarh', 'short_name': 'Chandigarh', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Chandigarh', 'short_name': 'CH', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Chandigarh, India', 'geometry': {'bounds': {'northeast': {'lat': 30.800142, 'lng': 76.8362439}, 'southwest': {'lat': 30.6700209, 'lng': 76.690814}}, 'location': {'lat': 30.7333148, 'lng': 76.7794179}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 30.800142, 'lng': 76.8362439}, 'southwest': {'lat': 30.6700209, 'lng': 76.690814}}}, 'place_id': 'ChIJa8lu5gvtDzkR_hlzUvln_6U', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:30.7333148
Longitude:76.7794179
Formatted Address:Chandigarh, India
cityname Ghaziabad
{'results': [{'address_components': [{'long_name': 'Ghaziabad', 'short_name': 'Ghaziabad', 'types': ['locality', 'political']}, {'long_name': 'Ghaziabad', 'short_name': 'Ghaziabad', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Uttar Pradesh', 'short_name': 'UP', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Ghaziabad, Uttar Pradesh, India', 'geometry': {'bounds': {'northeast': {'lat': 28.7969614, 'lng': 77.5562668}, 'southwest': {'lat': 28.6023449, 'lng': 77.23378989999999}}, 'location': {'lat': 28.6691565, 'lng': 77.45375779999999}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 28.7969614, 'lng': 77.5562668}, 'southwest': {'lat': 28.6023449, 'lng': 77.23378989999999}}}, 'place_id': 'ChIJ3w_FQbvxDDkRuph3atJv8OY', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:28.6691565
Longitude:77.45375779999999
Formatted Address:Ghaziabad, Uttar Pradesh, India
cityname Noida
{'results': [{'address_components': [{'long_name': 'Noida', 'short_name': 'Noida', 'types': ['locality', 'political']}, {'long_name': 'Gautam Buddh Nagar', 'short_name': 'Gautam Buddh Nagar', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Uttar Pradesh', 'short_name': 'UP', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Noida, Uttar Pradesh, India', 'geometry': {'bounds': {'northeast': {'lat': 28.6363011, 'lng': 77.50256329999999}, 'southwest': {'lat': 28.397206, 'lng': 77.2936967}}, 'location': {'lat': 28.5355161, 'lng': 77.3910265}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 28.6363011, 'lng': 77.50256329999999}, 'southwest': {'lat': 28.397206, 'lng': 77.2936967}}}, 'place_id': 'ChIJezVzMaTlDDkRP8B8yDDO_zc', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:28.5355161
Longitude:77.3910265
Formatted Address:Noida, Uttar Pradesh, India
cityname Jaipur
{'results': [{'address_components': [{'long_name': 'Jaipur', 'short_name': 'Jaipur', 'types': ['locality', 'political']}, {'long_name': 'Jaipur', 'short_name': 'Jaipur', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Rajasthan', 'short_name': 'RJ', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Jaipur, Rajasthan, India', 'geometry': {'bounds': {'northeast': {'lat': 27.0206722, 'lng': 75.94119069999999}, 'southwest': {'lat': 26.7497493, 'lng': 75.639925}}, 'location': {'lat': 26.9124336, 'lng': 75.7872709}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 27.0206722, 'lng': 75.94119069999999}, 'southwest': {'lat': 26.7497493, 'lng': 75.639925}}}, 'place_id': 'ChIJgeJXTN9KbDkRCS7yDDrG4Qw', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:26.9124336
Longitude:75.7872709
Formatted Address:Jaipur, Rajasthan, India
cityname Ahmedabad

{'results': [{'address_components': [{'long_name': 'Ahmedabad', 'short_name': 'Ahmedabad', 'types': ['locality', 'political']}, {'long_name': 'Ahmedabad', 'short_name': 'Ahmedabad', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Gujarat', 'short_name': 'GJ', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Ahmedabad, Gujarat, India', 'geometry': {'bounds': {'northeast': {'lat': 23.1378156, 'lng': 72.7053737}, 'southwest': {'lat': 22.9028759, 'lng': 72.4541115}}, 'location': {'lat': 23.022505, 'lng': 72.5713621}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 23.1863814, 'lng': 72.7696027}, 'southwest': {'lat': 22.8541054, 'lng': 72.3898825}}}, 'place_id': 'ChIJSdRbuoqEXjkRFmVPYRHdzk8', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:23.022505
Longitude:72.5713621
Formatted Address:Ahmedabad, Gujarat, India
cityname Gandhi Nagar
{'results': [{'address_components': [{'long_name': 'Gandhinagar', 'short_name': 'Gandhinagar', 'types': ['locality', 'political']}, {'long_name': 'Gandhinagar', 'short_name': 'Gandhinagar', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Gujarat', 'short_name': 'GJ', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Gandhinagar, Gujarat, India', 'geometry': {'bounds': {'northeast': {'lat': 23.2758847, 'lng': 72.6881217}, 'southwest': {'lat': 23.1655347, 'lng': 72.6029745}}, 'location': {'lat': 23.2156354, 'lng': 72.63694149999999}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 23.2758847, 'lng': 72.6881217}, 'southwest': {'lat': 23.1655347, 'lng': 72.6029745}}}, 'place_id': 'ChIJCWhtfJgrXDkRkQM-h6cGb_g', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:23.2156354
Longitude:72.63694149999999
Formatted Address:Gandhinagar, Gujarat, India
cityname Mumbai
{'results': [{'address_components': [{'long_name': 'Mumbai', 'short_name': 'Mumbai', 'types': ['locality', 'political']}, {'long_name': 'Mumbai', 'short_name': 'Mumbai', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Maharashtra', 'short_name': 'MH', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Mumbai, Maharashtra, India', 'geometry': {'bounds': {'northeast': {'lat': 19.2716339, 'lng': 72.9864994}, 'southwest': {'lat': 18.8928676, 'lng': 72.7758729}}, 'location': {'lat': 19.0759837, 'lng': 72.8776559}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 19.2716339, 'lng': 72.9864994}, 'southwest': {'lat': 18.8928676, 'lng': 72.7758729}}}, 'place_id': 'ChIJwe1EZjDG5zsRaYxkjY_tpF0', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:19.0759837
Longitude:72.8776559
Formatted Address:Mumbai, Maharashtra, India
cityname Thane
{'results': [{'address_components': [{'long_name': 'Thane', 'short_name': 'Thane', 'types': ['locality', 'political']}, {'long_name': 'Thane', 'short_name': 'Thane', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Maharashtra', 'short_name': 'MH', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Thane, Maharashtra, India', 'geometry': {'bounds': {'northeast': {'lat': 19.296441, 'lng': 73.0766616}, 'southwest': {'lat': 19.1313429, 'lng': 72.926259}}, 'location': {'lat': 19.2183307, 'lng': 72.9780897}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 19.296441, 'lng': 73.0766616}, 'southwest': {'lat': 19.1313429, 'lng': 72.926259}}}, 'place_id': 'ChIJWf12_vy45zsRgwLF94V9Ns8', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:19.2183307
Longitude:72.9780897
Formatted Address:Thane, Maharashtra, India
cityname Pune
{'results': [{'address_components': [{'long_name': 'Pune', 'short_name': 'Pune', 'types': ['locality', 'political']}, {'long_name': 'Pune', 'short_name': 'Pune', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Maharashtra', 'short_name': 'MH', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Pune, Maharashtra, India', 'geometry': {'bounds': {'northeast': {'lat': 18.6357545, 'lng': 73.9864569}, 'southwest': {'lat': 18.4134784, 'lng': 73.7394779}}, 'location': {'lat': 18.5204303, 'lng': 73.8567437}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 18.6357545, 'lng': 73.9864569}, 'southwest': {'lat': 18.4134784, 'lng': 73.7394779}}}, 'place_id': 'ChIJARFGZy6_wjsRQ-Oenb9DjYI', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:18.5204303
Longitude:73.8567437
Formatted Address:Pune, Maharashtra, India
cityname Nashik
{'results': [{'address_components': [{'long_name': 'Nashik', 'short_name': 'Nashik', 'types': ['locality', 'political']}, {'long_name': 'Nashik', 'short_name': 'Nashik', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Maharashtra', 'short_name': 'MH', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Nashik, Maharashtra, India', 'geometry': {'bounds': {'northeast': {'lat': 20.071733, 'lng': 73.91575809999999}, 'southwest': {'lat': 19.9101931, 'lng': 73.6912036}}, 'location': {'lat': 19.9974533, 'lng': 73.78980229999999}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 20.071733, 'lng': 73.91575809999999}, 'southwest': {'lat': 19.9101931, 'lng': 73.6912036}}}, 'place_id': 'ChIJsxSZsJDS3TsRXCEonV2EB8s', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:19.9974533
Longitude:73.78980229999999
Formatted Address:Nashik, Maharashtra, India
cityname Hyderabad
{'results': [{'address_components': [{'long_name': 'Hyderabad', 'short_name': 'Hyderabad', 'types': ['locality', 'political']}, {'long_name': 'Telangana', 'short_name': 'Telangana', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Hyderabad, Telangana, India', 'geometry': {'bounds': {'northeast': {'lat': 17.6078088, 'lng': 78.6561694}, 'southwest': {'lat': 17.2168886, 'lng': 78.1599217}}, 'location': {'lat': 17.385044, 'lng': 78.486671}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 17.6078088, 'lng': 78.6561694}, 'southwest': {'lat': 17.2168886, 'lng': 78.1599217}}}, 'place_id': 'ChIJx9Lr6tqZyzsRwvu6koO3k64', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:17.385044
Longitude:78.486671
Formatted Address:Hyderabad, Telangana, India
cityname Shamshabad
{'results': [{'address_components': [{'long_name': 'Shamshabad', 'short_name': 'Shamshabad', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': 'Hyderabad', 'short_name': 'Hyderabad', 'types': ['locality', 'political']}, {'long_name': 'Ranga Reddy', 'short_name': 'R.R. District', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Telangana', 'short_name': 'Telangana', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}, {'long_name': '501218', 'short_name': '501218', 'types': ['postal_code']}], 'formatted_address': 'Shamshabad, Hyderabad, Telangana 501218, India', 'geometry': {'bounds': {'northeast': {'lat': 17.2725407, 'lng': 78.47484229999999}, 'southwest': {'lat': 17.216891, 'lng': 78.3780523}}, 'location': {'lat': 17.25116, 'lng': 78.4377349}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 17.2725407, 'lng': 78.47484229999999}, 'southwest': {'lat': 17.216891, 'lng': 78.3780523}}}, 'place_id': 'ChIJXYOFH2m8yzsRHC55DF43h9Y', 'types': ['political', 'sublocality', 'sublocality_level_1']}], 'status': 'OK'}
Latitude:17.25116
Longitude:78.4377349
Formatted Address:Shamshabad, Hyderabad, Telangana 501218, India
cityname Bengaluru

{'results': [{'address_components': [{'long_name': 'Bengaluru', 'short_name': 'Bengaluru', 'types': ['locality', 'political']}, {'long_name': 'Bangalore Urban', 'short_name': 'Bangalore Urban', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Karnataka', 'short_name': 'KA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Bengaluru, Karnataka, India', 'geometry': {'bounds': {'northeast': {'lat': 13.173706, 'lng': 77.8826809}, 'southwest': {'lat': 12.7342888, 'lng': 77.3791981}}, 'location': {'lat': 12.9715987, 'lng': 77.5945627}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 13.173706, 'lng': 77.8826809}, 'southwest': {'lat': 12.7342888, 'lng': 77.3791981}}}, 'place_id': 'ChIJbU60yXAWrjsR4E9-UejD3_g', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:12.9715987
Longitude:77.5945627
Formatted Address:Bengaluru, Karnataka, India
cityname Bangalore
{'results': [{'address_components': [{'long_name': 'Bengaluru', 'short_name': 'Bengaluru', 'types': ['locality', 'political']}, {'long_name': 'Bangalore Urban', 'short_name': 'Bangalore Urban', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Karnataka', 'short_name': 'KA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Bengaluru, Karnataka, India', 'geometry': {'bounds': {'northeast': {'lat': 13.173706, 'lng': 77.8826809}, 'southwest': {'lat': 12.7342888, 'lng': 77.3791981}}, 'location': {'lat': 12.9715987, 'lng': 77.5945627}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 13.173706, 'lng': 77.8826809}, 'southwest': {'lat': 12.7342888, 'lng': 77.3791981}}}, 'place_id': 'ChIJbU60yXAWrjsR4E9-UejD3_g', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:12.9715987
Longitude:77.5945627
Formatted Address:Bengaluru, Karnataka, India
cityname Kolar
{'results': [{'address_components': [{'long_name': '4770', 'short_name': '4770', 'types': ['street_number']}, {'long_name': 'West Arrowhead Road', 'short_name': 'W Arrowhead Rd', 'types': ['route']}, {'long_name': 'Hermantown', 'short_name': 'Hermantown', 'types': ['locality', 'political']}, {'long_name': 'St. Louis County', 'short_name': 'St Louis County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Minnesota', 'short_name': 'MN', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}, {'long_name': '55811', 'short_name': '55811', 'types': ['postal_code']}], 'formatted_address': '4770 W Arrowhead Rd, Hermantown, MN 55811, USA', 'geometry': {'location': {'lat': 46.8213809, 'lng': -92.182098}, 'location_type': 'ROOFTOP', 'viewport': {'northeast': {'lat': 46.8227298802915, 'lng': -92.18074901970849}, 'southwest': {'lat': 46.8200319197085, 'lng': -92.18344698029149}}}, 'place_id': 'ChIJqYYO8TCzr1IRtuFjefNQZPE', 'types': ['car_dealer', 'car_repair', 'establishment', 'point_of_interest', 'store']}], 'status': 'OK'}
Latitude:46.8213809
Longitude:-92.182098
Formatted Address:4770 W Arrowhead Rd, Hermantown, MN 55811, USA
cityname Chennai
{'results': [{'address_components': [{'long_name': 'Chennai', 'short_name': 'Chennai', 'types': ['locality', 'political']}, {'long_name': 'Chennai', 'short_name': 'Chennai', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Tamil Nadu', 'short_name': 'TN', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Chennai, Tamil Nadu, India', 'geometry': {'bounds': {'northeast': {'lat': 13.2611661, 'lng': 80.33632279999999}, 'southwest': {'lat': 12.8338848, 'lng': 80.0817007}}, 'location': {'lat': 13.0826802, 'lng': 80.2707184}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 13.2611661, 'lng': 80.33632279999999}, 'southwest': {'lat': 12.8338848, 'lng': 80.0817007}}}, 'place_id': 'ChIJYTN9T-plUjoRM9RjaAunYW4', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:13.0826802
Longitude:80.2707184
Formatted Address:Chennai, Tamil Nadu, India
cityname Kanchipuram
{'results': [{'address_components': [{'long_name': 'Kanchipuram', 'short_name': 'Kanchipuram', 'types': ['locality', 'political']}, {'long_name': 'Kanchipuram', 'short_name': 'Kanchipuram', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Tamil Nadu', 'short_name': 'TN', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Kanchipuram, Tamil Nadu, India', 'geometry': {'bounds': {'northeast': {'lat': 12.8630496, 'lng': 79.74604939999999}, 'southwest': {'lat': 12.7966484, 'lng': 79.677757}}, 'location': {'lat': 12.8341735, 'lng': 79.7036402}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 12.8630496, 'lng': 79.74604939999999}, 'southwest': {'lat': 12.7966484, 'lng': 79.677757}}}, 'place_id': 'ChIJLfHH4PfCUjoRTSrLsYKGX94', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:12.8341735
Longitude:79.7036402
Formatted Address:Kanchipuram, Tamil Nadu, India
cityname Tiruvallur
{'results': [{'address_components': [{'long_name': 'Tiruvallur', 'short_name': 'Tiruvallur', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'Tamil Nadu', 'short_name': 'TN', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Tiruvallur, Tamil Nadu, India', 'geometry': {'bounds': {'northeast': {'lat': 13.5639311, 'lng': 80.3533479}, 'southwest': {'lat': 12.927394, 'lng': 79.2862619}}, 'location': {'lat': 13.2544335, 'lng': 80.0087746}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 13.5639311, 'lng': 80.3533479}, 'southwest': {'lat': 12.927394, 'lng': 79.2862619}}}, 'place_id': 'ChIJdQx5zBCQUjoR-L9nLEtv1I0', 'types': ['administrative_area_level_2', 'political']}], 'status': 'OK'}
Latitude:13.2544335
Longitude:80.0087746
Formatted Address:Tiruvallur, Tamil Nadu, India
cityname Kolkata
{'results': [{'address_components': [{'long_name': 'Kolkata', 'short_name': 'Kolkata', 'types': ['locality', 'political']}, {'long_name': 'Kolkata', 'short_name': 'Kolkata', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'West Bengal', 'short_name': 'WB', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Kolkata, West Bengal, India', 'geometry': {'bounds': {'northeast': {'lat': 23.0083628, 'lng': 88.5428696}, 'southwest': {'lat': 22.3436288, 'lng': 88.1165879}}, 'location': {'lat': 22.572646, 'lng': 88.36389500000001}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 23.0083628, 'lng': 88.5428696}, 'southwest': {'lat': 22.3436288, 'lng': 88.1165879}}}, 'place_id': 'ChIJZ_YISduC-DkRvCxsj-Yw40M', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:22.572646
Longitude:88.36389500000001
Formatted Address:Kolkata, West Bengal, India
cityname Howrah
{'results': [{'address_components': [{'long_name': 'Howrah', 'short_name': 'Howrah', 'types': ['locality', 'political']}, {'long_name': 'Howrah', 'short_name': 'Howrah', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'West Bengal', 'short_name': 'WB', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Howrah, West Bengal, India', 'geometry': {'bounds': {'northeast': {'lat': 22.6784507, 'lng': 88.36432459999999}, 'southwest': {'lat': 22.4351483, 'lng': 87.9875708}}, 'location': {'lat': 22.5957689, 'lng': 88.26363940000002}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 22.6784507, 'lng': 88.36432459999999}, 'southwest': {'lat': 22.4351483, 'lng': 87.9875708}}}, 'place_id': 'ChIJX8oAvkmC-DkR6NZLL8SWVD8', 'types': ['locality', 'political']}], 'status': 'OK'}
Latitude:22.5957689
Longitude:88.26363940000002
Formatted Address:Howrah, West Bengal, India
cityname Hooghly

{'results': [{'address_components': [{'long_name': 'Hooghly', 'short_name': 'Hooghly', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'West Bengal', 'short_name': 'WB', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'India', 'short_name': 'IN', 'types': ['country', 'political']}], 'formatted_address': 'Hooghly, West Bengal, India', 'geometry': {'bounds': {'northeast': {'lat': 23.22278, 'lng': 88.50384009999999}, 'southwest': {'lat': 22.59409, 'lng': 87.50858009999999}}, 'location': {'lat': 22.896256, 'lng': 88.24611829999999}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 23.22278, 'lng': 88.50384009999999}, 'southwest': {'lat': 22.59409, 'lng': 87.50858009999999}}}, 'place_id': 'ChIJN9hSE6mW-DkRTQBriGz_BNU', 'types': ['administrative_area_level_2', 'political']}], 'status': 'OK'}
Latitude:22.896256
Longitude:88.24611829999999
Formatted Address:Hooghly, West Bengal, India

In [100]:
# d = {
#     'cityname': [],
#     'lat': [],
#     'long': []
# }
# for city in final_lat_long:
#     d['cityname'].append(city); d['lat'].append(final_lat_long[city][0])
#     d['long'].append(final_lat_long[city][1])

city_lat_long_all = pd.DataFrame(final_lat_long)

In [91]:
# city_lat_long_all = pd.DataFrame(d)

In [103]:
x = city_lat_long_all.T
x.index

Index(['Ahmedabad', 'Bangalore', 'Bengaluru', 'Chandigarh', 'Chennai', 'Delhi',
       'Faridabad', 'Gandhi Nagar', 'Ghaziabad', 'Gurgaon', 'Hooghly',
       'Howrah', 'Hyderabad', 'Jaipur', 'Kanchipuram', 'Kolar', 'Kolkata',
       'Mohali', 'Mumbai', 'Nashik', 'Noida', 'Panchkula', 'Pune',
       'Shamshabad', 'Thane', 'Tiruvallur'],
      dtype='object')

In [63]:
city_lat_long_all.head()

,Ahmedabad,Bangalore,Bengaluru,Chandigarh,Chennai,Delhi,Faridabad,Gandhi Nagar,Ghaziabad,Gurgaon,...,Kolkata,Mohali,Mumbai,Nashik,Noida,Panchkula,Pune,Shamshabad,Thane,Tiruvallur
0,23.022505,12.971599,12.971599,30.733315,13.082680,28.704059,28.408912,23.215635,28.669156,28.459497,...,22.572646,30.704649,19.075984,19.997453,28.535516,30.694209,18.520430,17.251160,19.218331,13.254433
1,72.571362,77.594563,77.594563,76.779418,80.270718,77.102490,77.317789,72.636941,77.453758,77.026638,...,88.363895,76.717873,72.877656,73.789802,77.391026,76.860565,73.856744,78.437735,72.978090,80.008775

In [64]:
city_lat_long_all

,Ahmedabad,Bangalore,Bengaluru,Chandigarh,Chennai,Delhi,Faridabad,Gandhi Nagar,Ghaziabad,Gurgaon,...,Kolkata,Mohali,Mumbai,Nashik,Noida,Panchkula,Pune,Shamshabad,Thane,Tiruvallur
0,23.022505,12.971599,12.971599,30.733315,13.082680,28.704059,28.408912,23.215635,28.669156,28.459497,...,22.572646,30.704649,19.075984,19.997453,28.535516,30.694209,18.520430,17.251160,19.218331,13.254433
1,72.571362,77.594563,77.594563,76.779418,80.270718,77.102490,77.317789,72.636941,77.453758,77.026638,...,88.363895,76.717873,72.877656,73.789802,77.391026,76.860565,73.856744,78.437735,72.978090,80.008775

In [20]:
df4 =pd.read_csv('/home/prashant/Downloads/pincode/pincodes.csv')

In [21]:
df5 = pd.read_csv('/home/prashant/Downloads/pincode/missing_lat_long.csv')

In [22]:
results = df5.append(df4)

In [29]:
results.to_csv('merged_1.csv', index=False)

In [66]:
city_lat_long_all.to_csv('city_lat_long_all',index=False)

In [81]:
city_lat_long_all = pd.read_csv('city_lat_long_all')

In [84]:
city_lat_long_all.T.to_csv('city_lat_long_all', index=False)

In [97]:
res = pd.merge(df, city_lat_long_all, on='cityname')
df1.join(df2)

df3 = df1.set_index('p')

In [98]:
res

,pincode,districtname,statename,serviceable,cityname,lat,long
0,110001,Central Delhi,DELHI,1,Delhi,28.704059,77.102490
1,110002,Central Delhi,DELHI,1,Delhi,28.704059,77.102490
2,110003,Central Delhi,DELHI,1,Delhi,28.704059,77.102490
3,110004,Central Delhi,DELHI,1,Delhi,28.704059,77.102490
4,110005,Central Delhi,DELHI,1,Delhi,28.704059,77.102490
5,110006,Central Delhi,DELHI,1,Delhi,28.704059,77.102490
6,110007,North Delhi,DELHI,1,Delhi,28.704059,77.102490
7,110008,Central Delhi,DELHI,1,Delhi,28.704059,77.102490
8,110009,North West Delhi,DELHI,1,Delhi,28.704059,77.102490
9,110010,South West Delhi,DELHI,1,Delhi,28.704059,77.102490
10,110011,Central Delhi,DELHI,1,Delhi,28.704059,77.102490
11,110012,Central Delhi,DELHI,1,Delhi,28.704059,77.102490
12,110013,South Delhi,DELHI,1,Delhi,28.704059,77.102490
13,110014,South Delhi,DELHI,1,Delhi,28.704059,77.102490
14,110015,West Delhi,DELHI,1,Delhi,28.704059,77.102490
15,110016,South West Delhi,DELHI,1,Delhi,28.704059,77.102490
16,110017,South Delhi,DELHI,1,Delhi,28.704059,77.102490
17,110018,West Delhi,DELHI,1,Delhi,28.704059,77.102490
18,110019,South Delhi,DELHI,1,Delhi,28.704059,77.102490
19,110020,South Delhi,DELHI,1,Delhi,28.704059,77.102490
20,110021,South West Delhi,DELHI,1,Delhi,28.704059,77.102490
21,110022,South West Delhi,DELHI,1,Delhi,28.704059,77.102490
22,110023,South West Delhi,DELHI,1,Delhi,28.704059,77.102490
23,110024,South Delhi,DELHI,1,Delhi,28.704059,77.102490
24,110025,South Delhi,DELHI,1,Delhi,28.704059,77.102490
25,110026,West Delhi,DELHI,1,Delhi,28.704059,77.102490
26,110027,West Delhi,DELHI,1,Delhi,28.704059,77.102490
27,110028,South West Delhi,DELHI,1,Delhi,28.704059,77.102490
28,110029,South West Delhi,DELHI,1,Delhi,28.704059,77.102490
29,110030,South West Delhi,DELHI,1,Delhi,28.704059,77.102490
...,...,...,...,...,...,...,...
1448,712416,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1449,712417,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1450,712418,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1451,712419,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1452,712424,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1453,712426,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1454,712501,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1455,712502,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1456,712503,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1457,712504,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1458,712512,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1459,712513,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1460,712514,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1461,712515,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1462,712601,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1463,712602,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1464,712611,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1465,712612,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1466,712613,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1467,712614,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1468,712615,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1469,712616,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1470,712617,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1471,712701,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1472,712702,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1473,712704,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1474,712705,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1475,712706,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1476,712707,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118
1477,712708,Hooghly,WEST BENGAL,1,Hooghly,22.896256,88.246118

In [99]:
res.to_csv('all_city_along_with_pincode_lat_long.csv', index=False)